version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker-compose build
      - docker tag ecs-codepipeline_web:latest 551419436295.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-app-ecs:web
      - docker tag ecs-codepipeline_app:latest 551419436295.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-app-ecs:app
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 551419436295.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-app-ecs:web
      - docker push 551419436295.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-app-ecs:app
